sudo: false

language: java
jdk:
  - oraclejdk8
os:
  - linux

script: mvn clean cobertura:cobertura org.pitest:pitest-maven:mutationCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)