sudo: false

addons:
  sonarqube:
    token:
      secure: "b562657e9c20524337832edce610b861fa820cad"

language: java
script: mvn clean cobertura:cobertura org.pitest:pitest-maven:mutationCoverage sonar:sonar
jdk:
  - oraclejdk8
os:
  - linux

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script: mvn clean test org.pitest:pitest-maven:mutationCoverage sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)